version: '3.8'
services:
  rebase_db:
    image: postgres:latest
    working_dir: /app
    container_name: rebase_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rebase_labs_data
    ports:
      - "5432:5432"
    volumes:
      - exame_data:/var/lib/postgresql/data

  test:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
      - gemconfig:/root/.local/share/gem
    command: bash -c "bundle install && bundle exec rspec"
    environment:
      - RACK_ENV=test
    depends_on:
      - db-test
    networks:
      - tests

  db-test:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rebase_labs_data
    networks:
      tests:
        aliases:
          - rebase_db

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    image: ruby
    container_name: app
    environment:
      PGHOST: rebase_db
      PGUSER: user
      PGPASSWORD: password
      PGDATABASE: rebase_labs_data
      REDIS_URL: redis://redis:6379/0
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
      - gemconfig:/root/.local/share/gem
    ports:
      - "3000:3000"
    command: bash -c "bundle && ruby app/exams_importer.rb && rerun --background server.rb"

  redis-worker:
    image: ruby
    container_name: redis-worker
    environment:
      PGHOST: rebase_db
      PGUSER: user
      PGPASSWORD: password
      PGDATABASE: rebase_labs_data
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
      - gemconfig:/root/.local/share/gem
    command: bash -c "ruby app/worker.rb"

networks:
  tests:
volumes:
  exame_data:
  rubygems:
  gemconfig:
