#!/bin/bash

if ! sudo docker network inspect database_network >/dev/null 2>&1; then
  # Create the network if it doesn't exist
  sudo docker network create database_network
fi

# Check if the container exists
if ! sudo docker inspect rebase_db >/dev/null 2>&1; then
  # Run the PostgreSQL container
  sudo docker run -d --name rebase_db \
    --network database_network \
    -e POSTGRES_USER=user \
    -e POSTGRES_PASSWORD=password \
    -e POSTGRES_DB=rebase_labs_data \
    -p 5432:5432 \
    -v exame_data:/var/lib/postgresql/data \
    postgres:latest
fi

# Run the Ruby container
sudo docker run \
  --rm \
  --name rebase-labs \
  --network database_network \
  -e PGHOST=rebase_db \
  -e PGUSER=user \
  -e PGPASSWORD=password \
  -e PGDATABASE=rebase_labs_data \
  -w /app \
  -v $(pwd):/app \
  -p 3000:3000 \
  ruby \
  bash -c "bundle install && rerun --background server.rb"

